version: "3.1"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    image: node-postgres-express
    restart: always
    ports:
      - 3333:4000
    environment:
      - EXPRESS_PORT=4000
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
